name: build

on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout GitHub
        uses: actions/checkout@master

      - name: ğŸ”¨ Install dependencies
        run: |
          yarn
          cd demo
          yarn

      - name: ğŸ”§ Build demo
        run: |
          yarn docs

      - name: ğŸš€ Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: 'demo/dist'

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout GitHub
        uses: actions/checkout@master

      - name: ğŸ”¨ Install and Build
        run: |
          yarn
          yarn build

      - name: ğŸ”§ Setup Node
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: ğŸ“š Release
        uses: softprops/action-gh-release@v1
        with:
          files: '/dist'

      - name: ğŸ“¦ Publish to NPM
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}